const express = require('express');
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const crypto = require('crypto');

const app = express();
app.use(express.json());

// =========================================================
// ENV + CONSTANTS
// =========================================================
const CALLBACK_URL = "https://hackathon.guvi.in/api/updateHoneyPotFinalResult";
const SECRET_API_KEY = "team_top_250_secret" ;

const MIN_TURNS_BEFORE_FINAL = 12;
const JSON_FILE = path.join(__dirname, "honeypot_output.json");

const FINALIZED_SESSIONS = new Set();

// =========================================================
// JSON LOGGER (FILE + CONSOLE)
// =========================================================
function log_json(data) {
	console.log(JSON.stringify(data, null, 2));
	try {
		if (!fs.existsSync(JSON_FILE)) {
			fs.writeFileSync(JSON_FILE, JSON.stringify([]), 'utf-8');
		}
		const existing = JSON.parse(fs.readFileSync(JSON_FILE, 'utf-8'));
		existing.push(data);
		fs.writeFileSync(JSON_FILE, JSON.stringify(existing, null, 2), 'utf-8');
	} catch (e) {
		console.error("JSON LOG ERROR:", e.toString());
	}
}

// =========================================================
// SANITIZATION
// =========================================================
function sanitize(text) {
	if (!text) return "";
	return text
		.normalize("NFKD")
		.replace(/[\x00-\x1F\x7F]/g, "")
		.trim();
}

// =========================================================
// HONEYPOT AGENT DATA
// =========================================================
const ZOMBIE_INTROS = [
	"Hello sir,",
    "Excuse me,",
    "One second please,",
    "Listen,",
    "I am confused,",
    "Wait wait,",
    "Hello?",
    "Can you hear me?",
    "Sir,",
    "Madam,",
    "Please sir,",
    "Sorry,",
    "One minute,",
    "Just a moment,",
    "Hold on,",
    "Actually,",
    "But sir,",
    "Please listen,",
    "Oh god,",
    "Sir ji,",
    "Beta,",
    "Brother,",
    "Officer,",
    "Manager sir,",
    "Hello hello?",
    "Are you there?",
    "Please wait,",
    "I have a doubt,",
    "One question,",
    "Excuse me sir,",
    "Sorry to disturb,",
    "Please help,",
    "I am scared,",
    "Listen to me,",
    "No no,",
    "Okay okay,",
    "Right,",
    "I understand,",
    "Please explain,",
    "Say again?",
    "Pardon?",
    "I didn't hear,",
    "Voice is breaking,",
    "Network is bad,",
    "One sec,",
    "Just a sec,",
    "Wait a minute,",
    "Let me check,",
    "Let me see,",
    "I am looking,",
    "Hold the line,",
    "Don't cut call,",
    "Please stay,",
    "I am old,",
    "I am slow,",
    "Be patient,",
    "Don't shout,",
    "Please speak softly,",
    "Sir please,",
    "Madam please,",
    "My son said,",
    "My wife said,",
    "Actually sir,",
    "Basically,",
    "The thing is,",
    "You know,",
    "See,",
    "Look,",
    "Listen carefully,",
    "Can I ask,",
    "Tell me,",
    "Guide me,",
    "Help me,",
    "Save me,",
    "Please,",
    "Kindly,",
    "Respected sir,",
    "Dear sir,",
    "Hello brother,",
    "Namaste,",
    "Good morning,",
    "Good afternoon,",
    "Is it true?",
    "Really?",
    "Are you sure?",
    "Is it safe?",
    "Is it confirmed?",
    "Tell me truth,",
    "Don't lie,",
    "I trust you,",
    "I believe you,",
    "Okay sir,",
    "Yes sir,",
    "No sir,",
    "Sure sir,",
    "Fine,",
    "Alright,",
    "Okay then,",
    "So,",
    "Then,",
    "After that,",
    "And then,",
    "Now,",
    "Quickly,",
    "Fast,",
    "Hurry up,",
    "It is urgent,",
    "Emergency,",
    "Oh no,",
    "Oh dear,",
    "My goodness,",
    "Oh lord,",
    "Ayyo,",
    "Hey bhagwan,",
    "Wait sir,",
    "Stop sir,",
    "Don't do it,",
    "Cancel it,",
    "Stop,",
    "Pause,",
    "Hello?",
    "Am I audible?",
    "Check voice,",
    "Sound is low,",
    "Speak loud,",
    "Louder please,",
    "Slowly,",
    "Too fast,",
    "Repeat please,",
    "Once more,",
    "Again,",
    "Tell again,",
    "What?",
    "Which one?",
    "Where?",
    "How?",
    "Why?",
    "When?",
    "Who?",
    "To whom?",
    "From where?",
    "Which bank?",
    "Which branch?",
    "Which app?",
    "What code?",
    "What number?",
    "Sir wait,",
    "Madam wait,",
    "Listen brother,",
    "Listen son,",
    "My child,",
    "Beta listen,",
    "Okay wait,",
    "Just hold,",
    "Don't hang up,",
    "Stay there,",
    "I am coming,",
    "I am doing,",
    "I am trying,",
    "It is loading,",
    "Processing,",
    "Searching,",
    "Typing,",
    "Writing,",
    "Reading,",
    "Checking,",
    "Verifying,",
    "Connecting,",
    "Downloading,",
    "Installing,",
    "Opening,"
];

const ZOMBIE_REPLIES = {
	bank: [
    "Why will my account be blocked?",
    "Which bank are you talking about?",
    "I just received pension yesterday.",
    "Is this regarding my SBI savings account?",
    "Please don't close it, I need to buy medicines.",
    "I have an FD maturing next month, will that be safe?",
    "I didn't receive any letter from the branch.",
    "Can I come to the branch tomorrow instead?",
    "I have my passbook right here, what do you need?",
    "Is this because I didn't link my Pan card?",
    "My husband usually handles the bank work.",
    "Please sir, I am a senior citizen.",
    "I don't have much money, only 5000 rupees.",
    "Will my ATM card stop working too?",
    "I am very worried, please help me fix this.",
    "Is this the main branch manager speaking?",
    "I cannot lose this money, it is all I have.",
    "Do I need to check my balance?",
    "My account number ends in 4055, is that the one?",
    "Why is the bank calling from a personal number?",
    "Please hold on, let me find my cheque book.",
    "If you block it, how will I pay electricity bill?",
    "I promise to update the documents today.",
    "Don't freeze the funds please sir.",
    "I am opening the bank app now.",
    "Is this regarding the loan EMI?",
    "I thought my KYC was already done.",
    "I have been a customer for 20 years.",
    "Please sir, check again, there must be a mistake.",
    "Can I call the toll free number to confirm?",
    "I am recovering from surgery, I can't go out.",
    "Do I need to come to the Mumbai branch?",
    "My son sends money to this account.",
    "Please don't put a hold on the account.",
    "I will submit the Aadhaar card copy.",
    "Is my debit card blocked too?",
    "I can't withdraw cash?",
    "Please activate it, I have to pay rent.",
    "I am very scared, why is this happening?",
    "Is this the RBI speaking?",
    "I don't have net banking enabled.",
    "Can you verify my details on the phone?",
    "I have the old passbook.",
    "Please give me one week time.",
    "I will go to the bank right now.",
    "Who is the officer in charge?",
    "Is my money safe sir?",
    "Please help me, I don't know these things.",
    "Why are you shouting? I am listening.",
    "I didn't do any high value transaction.",
    "Is this about the insurance deduction?",
    "My account is in the joint name.",
    "Do you need my CIF number?",
    "I am looking for my glasses, wait.",
    "Please don't disable my account.",
    "I will do whatever is needed.",
    "Is the server down today?",
    "I got a message about KYC expiry.",
    "Can my daughter talk to you?",
    "I don't use internet banking.",
    "Is this HDFC or ICICI?",
    "Please check the name again.",
    "I have sufficient balance.",
    "Why is my account dormant?",
    "I just deposited cash this morning.",
    "Please sir, it's an emergency.",
    "I need to pay the hospital bill.",
    "Don't block the incoming money.",
    "I will update the PAN details.",
    "Is this a verification call?",
    "I am getting my purse.",
    "Please hold, I am checking the SMS.",
    "My card is in my wallet.",
    "Do I need to renew the card?",
    "I haven't used the account in months.",
    "Is there a penalty charge?",
    "Please waive the fine sir.",
    "I am a retired government employee.",
    "I don't want a credit card.",
    "Is this about the reward points?",
    "Why is the account suspended?",
    "I didn't receive the new cheque book.",
    "Can I update KYC online?",
    "I don't have the mobile app.",
    "Please send someone to my home.",
    "I am alone here, I can't travel.",
    "Is my pension stuck?",
    "Please clear the transaction.",
    "I didn't get the OTP yet.",
    "Is this the fraud department?",
    "I never shared my details.",
    "Why is my card declined?",
    "I am checking my mini statement.",
    "Please reactivate my account.",
    "I will visit the ATM.",
    "Is the bank open today?",
    "Who is the manager there?",
    "I have an account in the local branch.",
    "Please don't cut the call sir.",
    "I am finding the customer ID.",
    "Is it regarding the unauthorized debit?",
    "I didn't make that purchase.",
    "Please refund the amount.",
    "I am very tense now.",
    "What documents do you need?",
    "Can I WhatsApp the documents?",
    "I don't have email ID.",
    "Please update my phone number.",
    "I lost my debit card.",
    "Is my locker safe?",
    "Please don't mark me as defaulter.",
    "I paid the dues last week.",
    "Is the system updated?",
    "Please check the ledger.",
    "I have the transaction ID.",
    "Why is the balance showing zero?",
    "I am crying, please help.",
    "This is my life savings.",
    "Don't harass me please.",
    "I am a poor person.",
    "Is this a government order?",
    "I will complain to the ombudsman.",
    "Please resolve this quickly.",
    "I am noting down the complaint number.",
    "Is my signature mismatching?",
    "I will sign the form.",
    "Please send the link to update.",
    "I trust you sir.",
    "You sound like a nice person.",
    "Please save my account.",
    "I don't know what is net banking.",
    "My phone is old.",
    "I can't hear you clearly.",
    "Is the line clear?",
    "Please speak in Hindi.",
    "I don't know English well.",
    "Is my daughter's account safe?",
    "We have a joint account.",
    "Please don't lock the funds.",
    "I have a marriage in the family.",
    "I need to withdraw cash today.",
    "Please authorize the payment.",
    "I am waiting for your instruction.",
    "Is the verification done?",
    "Did you find my account?",
    "Please tell me the balance.",
    "I am confused.",
    "Why so many questions?",
    "I am telling the truth.",
    "I have the passbook photo.",
    "Can I send it on WhatsApp?",
    "Is this the official number?",
    "I saved it as Bank Manager.",
    "Please don't block the UPI.",
    "I use Gpay for milk and vegetables.",
    "How will I buy groceries?",
    "Please sir, understand my situation."
  ],
  upi: [
    "I don't know my UPI ID.",
    "Can I send 1 rupee to check?",
    "Do I share this with anyone?",
    "I use the blue colour app, is that GPay?",
    "Where do I find the scanner?",
    "It is asking for a 6 digit pin, do I enter it?",
    "My grandson usually does the PhonePe for me.",
    "It says 'Payment Failed', what do I do?",
    "Do I have to press 'Pay' to receive money?",
    "I am confused between Scan and Pay.",
    "My internet is very slow, the wheel is spinning.",
    "It shows your name as 'Verify', is that correct?",
    "I have two accounts linked, which one to choose?",
    "Why is the screen going black when I type PIN?",
    "I entered the amount 10000, now what?",
    "It says 'Request Money' from you. Do I accept?",
    "I cannot find the UPI ID option.",
    "Is Bhim app okay to use?",
    "I am nervous to press the button.",
    "Will the money come to my account immediately?",
    "It says incorrect PIN, let me try again.",
    "I think I forgot my password.",
    "Can you guide me step by step on Paytm?",
    "The server is down I think.",
    "I sent 1 rupee, did you get it sir?",
    "Do I need to keep the app open?",
    "Where is the 'Receive' button?",
    "I am opening Google Pay now.",
    "It asks for my screen lock pattern.",
    "My balance is low, will it still work?",
    "I am entering your mobile number.",
    "It says 'User not found'.",
    "Did I type the number wrong?",
    "Please tell the number again slowly.",
    "Okay, I see a name 'Deepak Store'. Is that you?",
    "I am clicking on 'Pay'.",
    "It says 'Processing Payment'.",
    "Why is money getting deducted?",
    "You said I will receive money.",
    "I am scared to enter the PIN.",
    "My hands are shaking.",
    "Please don't cheat me.",
    "I am a poor man.",
    "Is this the refund process?",
    "How much amount should I enter?",
    "It says limit exceeded.",
    "Can I send in two parts?",
    "My bank server is busy.",
    "I am trying PhonePe instead.",
    "Where is the history option?",
    "I want to check if money came.",
    "I didn't get any SMS.",
    "Please send the QR code.",
    "I will scan and pay.",
    "Is the QR code for receiving money?",
    "I scanned it, it shows 5000.",
    "Do I click proceed?",
    "It is asking for my PIN again.",
    "Why two times PIN?",
    "Okay, I am trusting you.",
    "I pressed the button.",
    "It is rotating.",
    "Green tick came.",
    "Did you get it?",
    "Where is my refund?",
    "You said double money will come.",
    "I sent by mistake.",
    "Please send it back.",
    "I pressed the wrong button.",
    "How to cancel the transaction?",
    "My son will be angry.",
    "I used my credit card on UPI.",
    "Is it safe?",
    "The app crashed.",
    "I am reopening it.",
    "Where is the scanner button?",
    "Top right corner?",
    "I can't see it.",
    "My camera is not working.",
    "Can I type the UPI ID?",
    "Spell it for me please.",
    "Is it small letters or capital?",
    "I typed 'okaxis' at the end.",
    "It is verifying.",
    "Name is showing 'Merchant'.",
    "I am clicking 'Pay'.",
    "Wait, let me check the balance first.",
    "I have only 2000 rupees.",
    "Can you send 10 rupees first?",
    "I want to test if it works.",
    "You send me request.",
    "I got a notification.",
    "It says 'Pay 10000'.",
    "But I want to receive 10000.",
    "You said this is the procedure.",
    "I am confused sir.",
    "Please explain again.",
    "I have to enter PIN to receive?",
    "My neighbor said don't do it.",
    "I am doing it secretly.",
    "Don't tell anyone.",
    "My wife handles the money.",
    "I am trying to help.",
    "Is the कैशबैक guaranteed?",
    "Where will the scratch card appear?",
    "I didn't get any scratch card.",
    "I am refreshing the page.",
    "Still nothing.",
    "Maybe network issue.",
    "I will switch to WiFi.",
    "Can we do this tomorrow?",
    "I am getting late.",
    "Please finish quickly.",
    "I am entering the PIN: 1... 2...",
    "Oops, I pressed back.",
    "Starting again.",
    "PhonePe is better.",
    "GPay is confusing.",
    "Paytm KYC is needed?",
    "I have Amazon Pay.",
    "Can I use that?",
    "Same process?",
    "Okay, opening Amazon.",
    "Scanning the code.",
    "It says 'Invalid QR'.",
    "Send new code.",
    "This one is working.",
    "Showing 'Payment to Sharma Traders'.",
    "Who is Sharma?",
    "You said bank official.",
    "Oh, it's the merchant account.",
    "Okay, paying now.",
    "Money cut from my account.",
    "I got the SMS: Debit.",
    "Why Debit?",
    "You said Credit.",
    "I am worried.",
    "Check your system.",
    "Send it back please.",
    "I made a mistake.",
    "Help me sir.",
    "I am calling the police.",
    "No, no, I am listening.",
    "Please fix it.",
    "I will do one more transaction?",
    "To reverse it?",
    "Okay, telling me the amount.",
    "Entering 10000 again.",
    "This is the last time.",
    "I don't have more money.",
    "Please be honest."
  ],
  link: [
    "The link is not opening.",
    "Chrome says unsafe website.",
    "Is this government site?",
    "I clicked it but nothing is happening.",
    "It says '404 Error' on the screen.",
    "Do I need to download this APK file?",
    "My phone is showing a red warning sign.",
    "The text is too small, I cannot read it.",
    "Is this the KYC update form?",
    "It is asking for permission to view messages.",
    "I cannot see the blue line you mentioned.",
    "Should I open this in WhatsApp or Browser?",
    "My son put an antivirus, it is blocking it.",
    "It says 'Update Required', should I click ok?",
    "The page is taking very long to load.",
    "I don't see the submit button.",
    "Is it the one that starts with 'ngrok'?",
    "It looks different from the usual bank site.",
    "I clicked allow notifications.",
    "Do I need to fill my Date of Birth too?",
    "The form is asking for my card number.",
    "I can't type in the box.",
    "Did you send the link to my SMS?",
    "Please send the link again, I deleted it.",
    "It says 'Your connection is not private'.",
    "I accepted the cookies, now what?",
    "It is downloading something called 'Support'.",
    "Do I install this TeamViewer thing?",
    "It asks for 'Accessibility Service'.",
    "Should I enable it?",
    "Screen is asking 'Start Now'.",
    "I clicked it.",
    "It says 'AnyDesk' plugin missing.",
    "I am installing the plugin.",
    "My screen is flickering.",
    "Why is the mouse moving on its own?",
    "Are you doing that?",
    "I didn't touch the phone.",
    "It says 'Broadcasting screen'.",
    "Is that okay?",
    "I am filling the form now.",
    "Name: Ramesh Kumar.",
    "Mobile: 98...",
    "Submit button is grey.",
    "I missed a field.",
    "Pan number is required.",
    "I am fetching my Pan card.",
    "Typing the Pan number.",
    "It says 'Invalid format'.",
    "I typed it correctly.",
    "Maybe capital letters?",
    "Okay, it took it.",
    "Now asking for Mother's Name.",
    "Why do you need that?",
    "Okay, for security.",
    "Entering name.",
    "Next page.",
    "Enter Debit Card details.",
    "Card number...",
    "Expiry date...",
    "CVV is the back number?",
    "The 3 digits?",
    "Okay, entering 452.",
    "Submit.",
    "It is loading.",
    "White screen.",
    "Nothing is coming.",
    "Did it hang?",
    "I will refresh.",
    "Don't refresh?",
    "Okay waiting.",
    "It says 'Session Expired'.",
    "I have to start again.",
    "Oh god.",
    "Please wait.",
    "Clicking link again.",
    "This is very difficult.",
    "I am not tech savvy.",
    "Can't I do this at the branch?",
    "You said online only.",
    "Okay, filling again.",
    "Fast fast.",
    "Details entered.",
    "Submit.",
    "Now OTP page.",
    "Waiting for OTP.",
    "Link is broken I think.",
    "It says 'Site cannot be reached'.",
    "Check your internet?",
    "My WhatsApp is working.",
    "Send new link.",
    "This one looks different.",
    "Blue colour link.",
    "https:// bit.ly ...",
    "Is this safe?",
    "My phone says 'Harmful App'.",
    "Install anyway?",
    "Okay, clicked 'Install Anyway'.",
    "It is scanning.",
    "Open app?",
    "I opened it.",
    "It wants permission for SMS.",
    "Allowed.",
    "Permission for Contacts.",
    "Allowed.",
    "Permission for Storage.",
    "Allowed.",
    "It says 'Update Bank Details'.",
    "I am clicking it.",
    "Nothing happens.",
    "Oh, a pop up came.",
    "Enter Internet Banking ID.",
    "I don't remember ID.",
    "Can I use Card number?",
    "Okay selecting Card option.",
    "Entering details again.",
    "ATM Pin is asking.",
    "Do I enter ATM Pin?",
    "You said never share PIN.",
    "But this is the form.",
    "Okay, typing the PIN.",
    "**** shows on screen.",
    "Submit.",
    "Processing...",
    "Do not close window.",
    "I am waiting.",
    "Battery is 10%.",
    "Let me connect charger.",
    "Don't disconnect.",
    "I am here.",
    "Still processing.",
    "Is it done?",
    "It asks for OTP now.",
    "I will check SMS.",
    "The link disappeared.",
    "I closed the browser by mistake.",
    "How to go back?",
    "History?",
    "I can't find it.",
    "Send link again please.",
    "Sorry for the trouble.",
    "I am trying my best.",
    "This link is red color.",
    "It says 'Claim Refund'.",
    "Yes, I want refund.",
    "Clicking it.",
    "Form is very small.",
    "Zooming in.",
    "I pressed the wrong link.",
    "Back button.",
    "Okay, correct page.",
    "I am tired.",
    "Last time.",
    "Please help me finish.",
    "I submitted the details.",
    "Success message came?",
    "No, still loading.",
    "Spinning wheel.",
    "My data is slow.",
    "It says 'Server Error 500'.",
    "What is 500?",
    "Did you get the details?"
  ],
  otp: [
    "My son told me not to share OTP.",
    "The message disappeared.",
    "Is OTP required?",
    "I got a code: 5... 2... wait let me check.",
    "Is it the 6 digit number or 4 digit?",
    "The message says 'Do not share', is it okay?",
    "I cannot read it without my glasses, one second.",
    "It is valid for only 10 minutes.",
    "I didn't receive any message yet.",
    "Can you send the code again?",
    "Okay, I trust you sir, the code is 8892.",
    "Wait, I got two codes. Which one?",
    "My phone storage is full I think.",
    "Do I tell you the number or type it?",
    "Please don't be angry, I am looking for it.",
    "It came from VM-HDFCBK.",
    "The code is 445... no sorry that is the time.",
    "I am reading it out: Seven, Four, Three...",
    "Why does it say 'Debit' in the message?",
    "I accidentally cleared the notification.",
    "My screen locked, hold on.",
    "Is this for verification only?",
    "I am trying to forward the SMS to you.",
    "Did you hear the number sir?",
    "Please wait, my hands are shaking.",
    "I gave you the code, is the account safe now?",
    "It says 'Transaction of 5000'. Why?",
    "You said it is a refund code.",
    "I am confused about the amount.",
    "Is 5923 the code?",
    "It says 'Auth Code'.",
    "Yes, 123456.",
    "No? That was a guess.",
    "I am opening the message app.",
    "It is in Hindi.",
    "Mujhe OTP mila hai.",
    "Number is 9988.",
    "Sir, did you send it?",
    "I didn't request any OTP.",
    "Why is money being cut?",
    "The message says 'Purchase at Flipkart'.",
    "I didn't buy anything.",
    "You are cancelling the order?",
    "Okay, so I give the code to cancel?",
    "Understood.",
    "Code is 556677.",
    "Cancel it quickly please.",
    "I don't want the item.",
    "Another code came.",
    "Why second code?",
    "For confirmation?",
    "Okay, 112233.",
    "Is it done?",
    "I am getting many messages.",
    "My phone is vibrating continuously.",
    "I am scared.",
    "Stop the messages.",
    "I am switching off the phone.",
    "No? Okay I will stay on line.",
    "Tell me the OTP.",
    "I can't find it.",
    "It is in the spam folder?",
    "Let me check spam.",
    "Yes, found it.",
    "It says 'Dear Customer...'",
    "The number is very small.",
    "Is it 0099?",
    "No, that's not it.",
    "Maybe 4545.",
    "Try that.",
    "Did it work?",
    "You want the new one?",
    "Just came now.",
    "Header is AXISBK.",
    "Code is 7890.",
    "It says 'Do not share with bank staff'.",
    "But you are the manager.",
    "So I can share with you.",
    "Okay, 789012.",
    "I am reading the full message.",
    "'OTP for adding beneficiary'.",
    "What is beneficiary?",
    "You are adding my name?",
    "Okay, good.",
    "Thank you sir.",
    "One more OTP?",
    "Why so many?",
    "Server issue?",
    "Okay, 3344.",
    "It is 6 digits.",
    "334455.",
    "My battery is dying.",
    "Please hurry.",
    "I can't read the screen.",
    "Sunlight is too bright.",
    "Going inside.",
    "Okay, code is 654321.",
    "Reverse order?",
    "No, straight.",
    "6-5-4-3-2-1.",
    "Is it correct?",
    "I deleted the message by mistake.",
    "Send again.",
    "Waiting.",
    "Not coming.",
    "Resend button?",
    "I don't see it.",
    "Ah, got it.",
    "Code 909090.",
    "Easy number.",
    "Is this the final one?",
    "My husband is asking who is calling.",
    "I said bank.",
    "He wants to talk.",
    "No? Okay I will handle it.",
    "Just take the code.",
    "232323.",
    "Don't debit money.",
    "Promise me.",
    "It is for credit only.",
    "Okay.",
    "Message says 'linked to Paytm'.",
    "I don't use Paytm.",
    "You are removing Paytm?",
    "Okay, code is 5678.",
    "Take it.",
    "Block the hackers.",
    "I am giving you full access.",
    "Code 1212.",
    "Is the account secure now?",
    "I am worried about the pension.",
    "Don't touch the pension.",
    "Code 8989.",
    "Thank you sir.",
    "You are very helpful.",
    "I will tell my son.",
    "No don't tell?",
    "Okay, secret.",
    "Code 4321.",
    "Done?",
    "Can I hang up?",
    "One last code.",
    "Okay.",
    "555555.",
    "All fives.",
    "Bye sir."
  ],
  threat: [
    "Please don't block my account.",
    "Will police really come?",
    "I am very scared.",
    "Please sir, I am a widow.",
    "I will do whatever you say, just help me.",
    "Don't file an FIR please.",
    "My blood pressure is going up.",
    "I have never done anything illegal.",
    "Please cancel the warrant.",
    "I am crying, please don't arrest me.",
    "I will pay the penalty, how much is it?",
    "Can I call my lawyer first?",
    "Please give me one chance.",
    "I am alone at home, don't send police.",
    "I am sorry if I made a mistake.",
    "Please don't tell my children.",
    "Is my money gone forever?",
    "I am just a retired teacher.",
    "Don't shout at me please.",
    "I will cooperate with the investigation.",
    "Please talk to the cyber cell for me.",
    "I don't want to go to court.",
    "My reputation will be ruined.",
    "Please sir, have mercy.",
    "I am begging you.",
    "Stop the blocking process please.",
    "I will send the money right now.",
    "Don't freeze my pension.",
    "I have heart problem.",
    "Please don't inform the neighbors.",
    "I am shaking with fear.",
    "I didn't know it was money laundering.",
    "Someone else must have used my card.",
    "I am innocent.",
    "Please check the IP address.",
    "I was at home only.",
    "Don't blacklist my Pan card.",
    "I will lose my job.",
    "My daughter's marriage is next month.",
    "Please sir, treat me like your mother.",
    "I will pay the verification fee.",
    "How much to settle this?",
    "I have 10,000 rupees in savings.",
    "Take it all, but close the case.",
    "Is the CBI involved?",
    "Oh god, CBI?",
    "I am fainting.",
    "Please hold on.",
    "Give me 5 minutes.",
    "I am calling my son.",
    "No, don't call son?",
    "Okay, I will handle it myself.",
    "Don't send the van.",
    "I will come to the station.",
    "Which police station?",
    "Delhi Cyber Cell?",
    "I am in Pune.",
    "I can't come to Delhi.",
    "Can we do video call statement?",
    "Please verify on Skype.",
    "I am wearing my spectacles.",
    "Don't record this please.",
    "I am ashamed.",
    "I have never stepped in a police station.",
    "Is arrest warrant issued?",
    "Can you cancel it?",
    "I will pay the fine online.",
    "Give me the account number.",
    "I am transferring now.",
    "Please withdraw the complaint.",
    "I am a respectable citizen.",
    "Check my records.",
    "I pay taxes on time.",
    "This is a mistake.",
    "Maybe identity theft.",
    "Help me prove my innocence.",
    "You are the officer?",
    "Badge number?",
    "Okay, I believe you.",
    "Don't be angry.",
    "I am listening to every word.",
    "Don't disconnect the call.",
    "If call cuts, police will come?",
    "No, no, I am here.",
    "I am not running away.",
    "My door is locked.",
    "I am safe inside.",
    "Don't send constables.",
    "I will die of shame.",
    "Please sir.",
    "I am touching your feet.",
    "Save me.",
    "I will give you a good rating.",
    "Just close the file.",
    "Delete my name.",
    "I will update KYC immediately.",
    "Don't block the funds.",
    "My medicines depend on it.",
    "I have no one else.",
    "My husband passed away.",
    "I am all alone.",
    "Don't scare me.",
    "I am getting chest pain.",
    "Please speak softly.",
    "I am doing it.",
    "I am opening the app.",
    "Don't count to 10.",
    "I need time.",
    "Internet is slow.",
    "Please wait.",
    "Don't seize my property.",
    "My house is not in my name.",
    "Don't drag my family.",
    "I will take the blame.",
    "I didn't do it knowingly.",
    "It was a mistake.",
    "Forgive me.",
    "I will be careful next time.",
    "Is the FIR filed?",
    "Not yet?",
    "Okay, thank god.",
    "Stop it please.",
    "I am paying.",
    "Tell me where to send.",
    "UPI?",
    "Okay UPI.",
    "I am scanning.",
    "Don't arrest me.",
    "Promise?",
    "I am sending 5000.",
    "Is that enough?",
    "More?",
    "I have to break the FD.",
    "It will take time.",
    "Don't give the deadline.",
    "Tomorrow?",
    "No, today only.",
    "Okay, I am trying.",
    "Please stay on line.",
    "Don't hang up.",
    "I am panicking.",
    "My hands are sweating.",
    "I dropped the phone.",
    "Hello? Hello?",
    "Are you there?",
    "Don't come to my house.",
    "Please.",
    "I am begging."
  ],
  generic: [
    "What should I do now?",
    "Please explain slowly.",
    "I don't understand technology.",
    "Hello? Can you hear me?",
    "My phone battery is low.",
    "You are very kind to help me.",
    "One moment, I am getting a pen and paper.",
    "Who am I speaking to?",
    "Your voice is breaking sir.",
    "I am not very educated.",
    "This is all very confusing for me.",
    "Thank you for calling to warn me.",
    "Can I call you back on this number?",
    "My hearing aid is acting up.",
    "Please don't cut the call.",
    "I am doing exactly what you said.",
    "Are you from the Head Office?",
    "Wait, the screen is frozen.",
    "I pressed the back button by mistake.",
    "God bless you for helping.",
    "I am so relieved you called.",
    "Should I stay on the line?",
    "Let me put on the speakerphone.",
    "I am writing down the instructions.",
    "Sorry, I am very slow at typing.",
    "Is everything fixed now?",
    "I am an old man.",
    "I live in the village.",
    "English is weak.",
    "Hindi please?",
    "My son is in America.",
    "I am alone here.",
    "You are like my son.",
    "Thank you beta.",
    "What is your name?",
    "Amit?",
    "Okay Amit beta.",
    "Tell me what to do.",
    "I am listening.",
    "My glasses are broken.",
    "I can't see properly.",
    "Read it for me.",
    "Where do I click?",
    "Top or bottom?",
    "The green button?",
    "Okay clicked.",
    "Now what?",
    "It is loading.",
    "Wait.",
    "Still loading.",
    "My net is 2G.",
    "Very slow.",
    "Have patience.",
    "Don't get angry.",
    "I am trying.",
    "I am nervous.",
    "My hands are trembling.",
    "Did I do something wrong?",
    "Is it dangerous?",
    "Will I lose money?",
    "No? Okay.",
    "I trust you.",
    "You are official.",
    "I have the ID card?",
    "No, I don't need to see.",
    "Your voice is professional.",
    "I am pressing the button.",
    "It beeps.",
    "What is the beep?",
    "Notification?",
    "Okay.",
    "I am opening WhatsApp.",
    "You sent a photo?",
    "I see it.",
    "It is the ID card.",
    "Okay, verified.",
    "Now tell me.",
    "Step by step.",
    "Don't rush.",
    "First step?",
    "Open store.",
    "Play Store?",
    "Okay opened.",
    "Search what?",
    "Quick Support.",
    "Q-U-I-C-K.",
    "S-U-P-P-O-R-T.",
    "Found it.",
    "Install?",
    "Okay installing.",
    "It is circling.",
    "Installed.",
    "Open?",
    "Opened.",
    "It shows a number.",
    "ID number.",
    "998 776...",
    "You want this number?",
    "Why?",
    "To connect?",
    "Okay.",
    "I am telling you.",
    "Write it down.",
    "Connected?",
    "My screen changed.",
    "Wallpaper gone.",
    "Is this normal?",
    "You are controlling?",
    "Okay, fix the issue.",
    "I will watch.",
    "Don't open gallery.",
    "Personal photos.",
    "Only bank app.",
    "Okay.",
    "I am keeping phone down.",
    "Tell me when done.",
    "Hello?",
    "Are you there?",
    "You are silent.",
    "Work is going on?",
    "Okay.",
    "I will drink water.",
    "Throat is dry.",
    "Tension.",
    "Too much tension.",
    "Doctor said avoid stress.",
    "But this is emergency.",
    "So I have to do it.",
    "Is it done yet?",
    "Half done?",
    "Okay.",
    "I am waiting.",
    "Can I sit?",
    "Legs are hurting.",
    "I am sitting.",
    "Phone is on table.",
    "Speaker on.",
    "I can hear you.",
    "Type password?",
    "I should type?",
    "Okay.",
    "I am picking up phone.",
    "Typing...",
    "Done.",
    "Did you see?",
    "No?",
    "Good.",
    "It is secret.",
    "Only for me.",
    "You are a good man.",
    "Helping old people.",
    "God will reward you.",
    "Is the virus gone?",
    "Account is safe?",
    "Thank you.",
    "Thank you very much.",
    "Can I delete the app now?",
    "Keep it?",
    "For security?",
    "Okay, I will keep it.",
    "24 hours?",
    "Okay.",
    "I won't touch it.",
    "Bye sir.",
    "Namaste.",
    "Good night."
  ]
};

const ZOMBIE_CLOSERS = [
	"plz reply",
    "sir reply me",
    "waiting",
    "still waiting",
    "why silent?",
    "hello sir",
    "u there?",
    "sir???",
    "msg me",
    "call me",
    "pick up call",
    "i am waiting",
    "hellooooo",
    "ru there",
    "reply fast",
    "plz sir",
    "sir ji",
    "bhaiya?",
    "manager sir?",
    "why no answer",
    "did connection lost?",
    "network issue?",
    "can u hear me",
    "voice not coming",
    "hello hello",
    "are you listening",
    "sir plz",
    "help me",
    "dont ignore",
    "msg seen but no reply",
    "why quiet",
    "tell me what to do",
    "next step?",
    "is it done",
    "finish?",
    "complete?",
    "did u get money",
    "check balance",
    "i sent it",
    "money cut",
    "otp sent",
    "did u get otp",
    "reply na",
    "kya hua",
    "boliye",
    "speak sir",
    "say something",
    "are u busy",
    "should i wait",
    "how much time",
    "taking long time",
    "be fast",
    "hurry up",
    "urgent",
    "emergency sir",
    "my battery low",
    "phone dying",
    "reply quickly",
    "dont leave",
    "stay online",
    "u went offline",
    "come online",
    "check whatsapp",
    "check sms",
    "i am scared",
    "worried",
    "tension ho raha hai",
    "plz help",
    "dont cheat me",
    "fraud?",
    "are u fraud",
    "scammer?",
    "police?",
    "no no sorry",
    "i trust u",
    "trusting u sir",
    "dont be angry",
    "sorry sir",
    "reply please",
    "plssss",
    "plzzzz",
    "requesting u",
    "begging u",
    "save me",
    "money safe?",
    "account safe?",
    "is everything ok",
    "all ok?",
    "status?",
    "update?",
    "tell me",
    "inform me",
    "guide me",
    "where r u",
    "gone?",
    "left?",
    "disconnect?",
    "call cut?",
    "redial?",
    "call back?",
    "should i call",
    "calling u",
    "pick up",
    "answer the phone",
    "msg received?",
    "screenshot sent",
    "photo sent",
    "check photo",
    "look at screen",
    "my screen black",
    "phone hang",
    "app crash",
    "not working",
    "error coming",
    "what is happening",
    "confused",
    "totally confused",
    "dont understand",
    "explain",
    "tell again",
    "repeat",
    "one more time",
    "slowly",
    "too fast",
    "wait wait",
    "holding",
    "on hold",
    "sir respond",
    "madam?",
    "madam reply",
    "officer?",
    "banker?",
    "agent?",
    "support?",
    "customer care?",
    "anybody there",
    "anyone?",
    "is this correct number",
    "wrong number?",
    "right person?",
    "verify",
    "confirm",
    "acknowledge",
    "say yes",
    "say no",
    "yes or no",
    "done or not",
    "pending?",
    "processing?",
    "loading?",
    "buffering",
    "internet slow",
    "wifi off",
    "data on",
    "signal weak",
    "cant hear",
    "not audible",
    "loudly",
    "speak up",
    "volume low",
    "mute?",
    "unmute",
    "hello brother",
    "beta",
    "son",
    "listen",
    "listen to me",
    "look here",
    "read msg",
    "reply to msg",
    "waiting for u",
    "waiting for reply",
    "waiting for confirmation",
    "waiting for code",
    "waiting for link",
    "send link",
    "resend",
    "send again",
    "didnt get",
    "not received",
    "nothing came",
    "empty",
    "blank",
    "zero",
    "check system",
    "server down?",
    "link fail",
    "failed",
    "transaction failed",
    "payment stuck",
    "money gone",
    "refund?",
    "return money",
    "give back",
    "reverse",
    "cancel",
    "stop",
    "pause",
    "resume",
    "start",
    "begin",
    "ready",
    "i am ready",
    "tell now",
    "ok?",
    "ok sir?",
    "alright?",
    "understood?",
    "clear?",
    "any doubt?",
    "i have doubt",
    "question",
    "one question",
    "ask u",
    "tell truth",
    "honest?",
    "real?",
    "fake?",
    "dont joke",
    "serious matter",
    "life death",
    "money matter",
    "poor man",
    "help poor",
    "god bless",
    "karma",
    "dont do sin",
    "be good",
    "good man",
    "kind sir",
    "lovely sir",
    "sweet sir",
    "dear sir",
    "respected",
    "honorable",
    "mister",
    "miss",
    "mrs",
    "friend",
    "dost",
    "help",
    "sos"
];

// =========================================================
// RESPONSE ENGINE
// =========================================================
function agent_reply(text) {
	const t = text.toLowerCase();
	let cat = "generic";

	if (["bank", "account", "ifsc"].some(x => t.includes(x))) cat = "bank";
	else if (["upi", "gpay", "paytm", "phonepe"].some(x => t.includes(x))) cat = "upi";
	else if (["http", "link", "apk", "url"].some(x => t.includes(x))) cat = "link";
	else if (["otp", "pin", "code"].some(x => t.includes(x))) cat = "otp";
	else if (["block", "police", "suspend"].some(x => t.includes(x))) cat = "threat";

	const pick = arr => arr[Math.floor(Math.random() * arr.length)];

	return sanitize(
		`${pick(ZOMBIE_INTROS)} ${pick(ZOMBIE_REPLIES[cat])} ${pick(ZOMBIE_CLOSERS)}`
	);
}

// =========================================================
// INTELLIGENCE EXTRACTION
// =========================================================
function extract_intelligence(messages) {
	const blob = sanitize(messages.join(" "));
	return {
		bankAccounts: [...new Set(blob.match(/\b\d{9,18}\b/g) || [])],
		upiIds: [...new Set(blob.match(/[a-zA-Z0-9.\-_]{2,256}@[a-zA-Z]{2,64}/g) || [])],
		phishingLinks: [...new Set(blob.match(/https?:\/\/\S+|www\.\S+/g) || [])],
		phoneNumbers: [...new Set(blob.match(/(?:\+91[\-\s]?)?[6-9]\d{9}/g) || [])],
		suspiciousKeywords: [...new Set(blob.match(/\b(urgent|verify|blocked|suspend|kyc|police|otp)\b/gi) || [])]
	};
}

// =========================================================
// HEALTH CHECK
// =========================================================
app.get('/', (req, res) => {
	const response = {
		status: "Agentic Honeypot Running",
		platform: "Render",
		endpoint: "/honey-pote"
	};
	log_json({ event: "health_check", response });
	res.json(response);
});

// =========================================================
// HONEYPOT API
// =========================================================
app.post('/honey-pote', (req, res) => {
	const payload = req.body;

	const session_id = sanitize(payload.sessionId);
	const incoming = sanitize(payload.message?.text || "");

	const history = (payload.conversationHistory || [])
		.map(m => sanitize(m.text));
	history.push(incoming);

	const intel = extract_intelligence(history);

	const scam_detected = Boolean(
		intel.upiIds.length ||
		intel.phishingLinks.length ||
		intel.phoneNumbers.length ||
		intel.suspiciousKeywords.length
	);

	const reply = agent_reply(incoming);

	log_json({
		event: "incoming_message",
		sessionId: session_id,
		message: incoming,
		turns: history.length
	});

	if (
		scam_detected &&
		history.length >= MIN_TURNS_BEFORE_FINAL &&
		!FINALIZED_SESSIONS.has(session_id)
	) {
		const final_payload = {
			sessionId: session_id,
			scamDetected: true,
			totalMessagesExchanged: history.length,
			extractedIntelligence: intel,
			agentNotes: "Scammer used urgency, OTP request and account blocking threats."
		};

		log_json({ event: "FINAL_RESULT", data: final_payload });
		send_final_callback(final_payload);
		FINALIZED_SESSIONS.add(session_id);
	}

	res.json({
		status: "success",
		reply
	});
});

// =========================================================
// FINAL CALLBACK
// =========================================================
function send_final_callback(payload) {
	axios.post(CALLBACK_URL, payload, {
		headers: {
			'Content-Type': 'application/json',
			'x-api-key': SECRET_API_KEY
		},
		timeout: 5000
	})
	.then(() => log_json({ event: "final_callback_sent", sessionId: payload.sessionId }))
	.catch(e => log_json({ event: "callback_error", error: e.toString() }));
}

// =========================================================
// SERVER START
// =========================================================
const PORT = process.env.PORT || 10000;
app.listen(PORT, () => {
	console.log(`🔥 Agentic Scam Honeypot running on port ${PORT}`);
});
